name: Build docker image and publish to GitHub Pages
on:
  push:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Setup env
      run: |
        echo "::set-env name=CONTAINER_IMAGE::docker.pkg.github.com/${GITHUB_REPOSITORY,,}/${GITHUB_REPOSITORY##*/}:${{github.sha}}"
        echo "::set-env name=CONTAINER_IMAGE_LATEST::docker.pkg.github.com/${GITHUB_REPOSITORY,,}/${GITHUB_REPOSITORY##*/}:latest"
    - name: Docker build
      run: |
        docker login -u $GITHUB_ACTOR -p ${{secrets.GITHUB_TOKEN}} docker.pkg.github.com
        docker build -t $CONTAINER_IMAGE -t $CONTAINER_IMAGE_LATEST .
    - name: Docker push
      run: |
        docker push $CONTAINER_IMAGE
        docker push $CONTAINER_IMAGE_LATEST

  publish:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Page Build
      env:
        CI: true
      run: |
        npm install
        npm run build --if-present
    - name: Page Publish
      run: |
        cd dist
        git init
        git config user.name $GITHUB_ACTOR
        git config user.email $GITHUB_ACTOR@users.noreply.github.com
        git add -A
        git commit -m "Deploy"
        git push -f https://$GITHUB_ACTOR:${{secrets.GITHUB_TOKEN}}@github.com/$GITHUB_REPOSITORY.git master:gh-pages
